databases:
  - name: expense-db
    databaseName: expensetracker
    user: root
    plan: free

services:
  # Backend Service
  - type: web
    name: backend
    env: docker
    dockerContext: backend/ExpenseTracker
    dockerfilePath: backend/ExpenseTracker/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: expense-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: expense-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: expense-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: expense-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: expense-db
          property: password
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SPRING_MAIL_HOST
        sync: false
      - key: SPRING_MAIL_PORT
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: expense-tracker
    env: docker
    dockerContext: frontend/expense-tracker-frontend
    dockerfilePath: frontend/expense-tracker-frontend/Dockerfile
    plan: free
