databases:
  - name: expense-db
    databaseName: expensetracker
    user: root
    plan: free

services:
  # Backend Service
  - type: web
    name: backend
    env: docker
    dockerContext: backend/ExpenseTracker
    dockerfilePath: backend/ExpenseTracker/Dockerfile
    plan: free
    envVars:
      # We explicitly set the JDBC URL to bypass Render's 'postgres://' DATABASE_URL
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://expense-db:5432/expensetracker
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: expense-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: expense-db
          property: password
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SPRING_MAIL_HOST
        sync: false
      - key: SPRING_MAIL_PORT
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false

  # Frontend Service
  - type: web
    name: frontend
    env: docker
    dockerContext: frontend/expense-tracker-frontend
    dockerfilePath: frontend/expense-tracker-frontend/Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        value: http://backend:8080
