spring.application.name=ExpenseTracker

# The real datasource values are injected via Docker ENTRYPOINT
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/expensetracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Brevo Email Configuration
brevo.api.key=${BREVO_API_KEY:NO_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL:sahilmahajan2804@gmail.com}
brevo.sender.name=Expense Tracker

# File Upload Configuration
file.upload-dir=${FILE_UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# CORS Configuration
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:http://localhost:4200}
